### ISSUE TITLE
Cannot Start Hunter Douglas Platinum Plugin

### ISSUE THREAD

**Issue by imrichbiotch** [schemers/homebridge-hunterdouglas-platinum#5]
Hi there,

I'm pretty new to using Homebridge or GitHub for that matter. I found this while trying to find a way to avoid spending a LOT of money to "upgrade" from Hunter Douglas Platinum to PowerView. This seems like a great solution.

While setting up this plugin, I seem to keep hitting the same issue when I restart Homebridge.

[HunterDouglasPlatinum] unable to get blind config: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 595f02ec-e2f7-4e27-aba7-07dbf98852e7

I've tried removing the accessories and persist folder in ~/.homebridge, but I still keep hitting the issue. I've also tried to rename a few of the blinds to see if there's any issues there, but I did not find any.

Here's the full error:

[5/17/2020, 1:36:34 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/17/2020, 1:36:34 PM] [HB Supervisor] Started Homebridge v1.1.0 with PID: 38284
[5/17/2020, 1:36:34 PM] Loaded config.json with 0 accessories and 2 platforms.
[5/17/2020, 1:36:34 PM] ---
[5/17/2020, 1:36:34 PM] Loaded plugin: homebridge-config-ui-x@4.19.0
[5/17/2020, 1:36:34 PM] Registering platform 'homebridge-config-ui-x.config'
[5/17/2020, 1:36:34 PM] ---
[5/17/2020, 1:36:34 PM] Loaded plugin: homebridge-hunterdouglas-platinum@1.4.0
[5/17/2020, 1:36:34 PM] Registering platform 'homebridge-hunterdouglas-platinum.HunterDouglasPlatinum'
[5/17/2020, 1:36:34 PM] ---
[5/17/2020, 1:36:34 PM] Loading 2 platforms...
[5/17/2020, 1:36:34 PM] [Config] Initializing config platform...
[5/17/2020, 1:36:34 PM] [Config] Running in Service Mode
[5/17/2020, 1:36:34 PM] [HunterDouglasPlatinum] Initializing HunterDouglasPlatinum platform...
[5/17/2020, 1:36:34 PM] [HunterDouglasPlatinum] Fetching Blind Info...
[5/17/2020, 1:36:35 PM] [HunterDouglasPlatinum] connected: 000B3C61AB47 2018-HD gateway 2.18a (getBlindConfig)
[5/17/2020, 1:36:35 PM] [HunterDouglasPlatinum] found 14 accessories
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Master Suite Bedside Window'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Master Suite Sliding Door'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Master Suite Bench Window'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Silhouette  Bar Silhouette'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Silhouette  Corner Sideyard Silhouet'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Silhouette  Corner Window Backyard'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Dining Luminette Sliding Doors'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Dark Bar Blackout'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Dark Corner Sideyard Blackout'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Dark Corner Backyard Blackout'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Master Suite'...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Great Room Silhouette '...
[5/17/2020, 1:36:35 PM] Initializing platform accessory 'Dining Luminette'...
[5/17/2020, 1:36:35 PM] [HunterDouglasPlatinum] unable to get blind config: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 595f02ec-e2f7-4e27-aba7-07dbf98852e7
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:429:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:416:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at /usr/local/lib/node_modules/homebridge-hunterdouglas-platinum/index.js:99:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:38284) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-hunterdouglas-platinum/index.js:103:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:38284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Appreciate any help I can get! Would love for this to work if we can resolve it!

**Comment by schemers** [comment]
Hi. do you by chance happen to have a room with a single blind in it? 

I use the following when generating a stable id:

`this.uuid_base = uuid.generate(platform.device_id + ':' + roomId + ':' + blindId)`

And when I constructed the virtual blind for the whole room, `blindId` is normally a comma-separated list of ids. If you have only a single blind in the room it will generate the same ID for the actually blind and blind for the whole room.

The fix should be simple.

**Comment by imrichbiotch** [comment]
Yes! In fact I do. The room labeled "Dining Luminette" only has one shade in it.

**Comment by schemers** [comment]
I think the simplest and most logical fix is to not create a virtual room blind if a room only has a single shade in it. I should be able to push out something shortly.

If you want to try a quick test you could set `createVirtualRoomBlind`  to `false` in the config file, which would work around the bug by not creating any virtual room blinds.

**Comment by schemers** [comment]
I just published v1.4.1 which should hopefully fix the duplicate id problem

**Comment by imrichbiotch** [comment]
Thanks matey! I'll give it a go right now

**Comment by imrichbiotch** [comment]
Looks like I was able to get it to work by turning off the Virtual Room Feature. When it was left on, it appears to still have the error.

This is **GREAT** btw. Thanks for developing this. Is there a way that shades that have Vanes Open/Close to be classified as a different type of shade?

**Comment by schemers** [comment]
oops, sorry. When checking number of blinds in a room I put in `>0` instead of `>1`. 

v1.4.2 (just published) should hopefully actually fix it.

**Comment by schemers** [comment]
I'm not familiar with those type of shades (mine are just top down). @twangus recently added support for top-down / bottom-up shades, but not sure if they are same thing.

If you know how to start home bridge with debug turned on (`-D` argument) it will dump out your blind config in the logs, which might help.

**Comment by imrichbiotch** [comment]
@schemers works like a charm with the latest update! thank you again! you've modernize my home!

Couldn't get the debug option to work to output things.
